services:
  postgre:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    ports:
      - 5432:5432
      # - máquina local: container
  kubenews: #depends on postgres
    depends_on:
      - postgre
    image: alenerick/kube-news
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
     - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: postgres1234
      DB_HOST: postgre
networks:
  kubenews_net:
    driver: bridge
